In [1]:
import tensorflow as tf

In [2]:
tf.executing_eagerly()

True

In [3]:
x = [[2,]]

In [4]:
m = tf.matmul(x,x)

In [5]:
print(m)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [6]:
m.numpy()

array([[4]])

In [9]:
a = tf.constant([[1,2],
                [3,4]])

In [10]:
a.numpy()

array([[1, 2],
       [3, 4]])

In [13]:
b = tf.add(a,1)

In [14]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [20]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [21]:
import numpy as np

In [22]:
d = np.array([[5,6],[7,8]])

In [23]:
d

array([[5, 6],
       [7, 8]])

In [26]:
(a+d).numpy()

array([[ 6,  8],
       [10, 12]])

In [27]:
g = tf.convert_to_tensor(10)

In [28]:
g

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [29]:
float(g)

10.0

In [15]:
c = tf.multiply(a,b)

In [16]:
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [17]:
num = tf.convert_to_tensor(10)

In [18]:
num

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [19]:
for i in range(num.numpy()):
    i = tf.constant(i)
    if int(i%2) == 0:
        print('even')
    else:
        print('add')

even
add
even
add
even
add
even
add
even
add
